perl-Net-RawIP
perl-NetPacket
perl-net-dns
perl-Net-DNS-SEC
perl-Net-DNS-Resolver-Programmable
perl-Net-DNS-Resolver-Mock
perl-Net-DNS-Native
perl-net-ip
perl-Net-IPv6Addr
perl-Net-IPv4Addr
perl-digest-hmac
perl-digest-sha1
perl-Net-Pcap
perl-IO-Interface
perl-Archive-Zip
perl-PAR-Dist
perl-inc-latest
perl-Module-Build
sqlninja
metasploit
